library(languageR)
library(tidyverse)
library(gdata)
library(MASS)
library(magrittr)
library(ggplot2)
theme_set(theme_bw(base_family = "Times"))
library(car, warn.conflicts = FALSE)
library(brms)
library(xtable)
library(rstan)
rstan_options(auto_write = TRUE)
rstan_options(silent = TRUE, open_progress= FALSE,show_messages= FALSE)
rstan_options(javascript = FALSE)
## Use all the cores:
options(mc.cores = parallel::detectCores())
